# Common Features
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
# TIME_FIELD: timestamp

filter_out_cod_start_users: True

inter_file_name: 'train_splitted.inter'


# name of features
vision_feature_file: 'image.npy'
text_feature_file: 'text.npy'
#user_graph_dict_file: 'user_graph_dict.npy'

# field_separator: "\t"
